version: '3'

services:
  api:
    container_name: boilerplate_api
    image: node:12
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    networks:
      - db
    depends_on:
      - mongodb
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - ./.env

  mongodb:
    container_name: boilerplate_mongo
    image: mongo
    networks:
      - db
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./.env

networks:
  db:

volumes:
  mongodb:
